[package]
name = "eva01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = { version = "0.30.1", features = ["async"] }
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
anyhow = "1.0.79"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bincode = "1.3.3"
bytemuck = "1.14.0"
bytes = "1.5.0"
clap = { version = "4.5.4", features = ["derive"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
env_logger = "0.11.3"
fixed = "1.24.0"
fixed-macro = "1.2.0"
futures = "0.3.30"
futures-sink = "0.3.30"
jupiter-swap-api-client = "0.1.0"
log = "0.4.21"
marginfi = { git = "https://github.com/mrgnlabs/marginfi-v2", branch = "cavey/t22-upgraded-anchor", features = [
    "mainnet-beta",
    "client",
    "no-entrypoint",
] }
jito-protos = { git = "https://github.com/LevBeta/jito-rs", branch = "1.18.17"}
jito-searcher-client = { git = "https://github.com/LevBeta/jito-rs", branch = "1.18.17"}
num-traits = "0.2.18"
rayon = "1.10.0"
serde = "1.0.197"
serde_json = "1.0.116"
sha2 = "0.10.8"
solana-account-decoder = "1.18.17"
solana-client = "1.18.17"
solana-program = "1.18.17"
solana-rpc-client-api = "1.18.17"
solana-sdk = "1.18.17"
solana-address-lookup-table-program = "1.18.17"
spl-associated-token-account = "2.0.0"
spl-token = "=4.0.0"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt", "macros"] }
toml = "0.8.12"
tonic = "0.10.2"
tonic-health = "0.10.2"
yellowstone-grpc-client = { git = "https://github.com/LevBeta/yellowstone-grpc", branch = "1.18.17" }
yellowstone-grpc-proto = { git = "https://github.com/LevBeta/yellowstone-grpc", branch = "1.18.17" }
