name: Rust CI - cargo clippy

on:
  pull_request:
    types: [opened, synchronize, reopened, assigned, labeled, ready_for_review]

jobs:
    cargo-clippy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Rust toolchain
          uses: dsherret/rust-toolchain-file@v1
          with:
            toolchain: 1.71
            components: clippy, rustfmt
            override: true
        - name: Clippy Lint
          run: | 
            cargo clippy
