name: Rust CI - cargo fmt

on:
  pull_request:
    types: [opened, synchronize, reopened, assigned, labeled, ready_for_review]

jobs:
    cargo-fmt:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
          apt install -y unzip
          unzip protoc-25.1-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - name: Check Formatting
        run: |
          cargo fmt -- --check
